### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by roughike** [roughike/inKino#25]
Currently, every message and label is hardcoded, and the app works in English only. Localize the app the support both English and Finnish.

Tasklist:
- [x] Extract all hardcoded strings into a localization file
- [x] Introduce English and Finnish localizations
- [x] Modify the Finnkino API client to drop the `en` [from the URLs](https://github.com/roughike/inKino/blob/master/lib/data/networking/finnkino_api.dart#L13) when the detected language is Finnish

**Comment by klavs** [comment]
@roughike isn't this done with the new multi-platform refactor?

**Comment by roughike** [comment]
Yes, this is now indeed done!
