### ISSUE TITLE
Issue with loading Mockito

### ISSUE THREAD

**Issue by mikeroosa** [roughike/inKino#61]
When I first clone the repo and open it, I'm seeing this error:
[inKino] flutter packages get
Running "flutter packages get" in inKino...
Incompatible version constraints on mockito:
- flutter_test 0.0.0 depends on version 2.2.3
- inkino depends on version 3.0.0-alpha+3
pub get failed (1)
exit code 1

**Comment by roughike** [comment]
Are you using the latest Flutter version, which was released yesterday? Could you run `flutter upgrade` and see if it works for you after that?

**Comment by mikeroosa** [comment]
I did upgrade yesterday. Hmm, flutter upgrade gives this message so I'll try to resolve that:
Upgrading Flutter from d:\flutter...
fatal: unable to access 'https://github.com/flutter/flutter.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by roughike** [comment]
I have a potential fix coming up here: #62

It'll be merged to develop after the Travis build finishes, could you test if it works for you after that?

**Comment by mikeroosa** [comment]
Sure

**Comment by mikeroosa** [comment]
flutter upgrade is taking a long time to run. I must have had something out of date. will update when it's done.

**Comment by roughike** [comment]
No problem! The PR I merged should make the project to be able to build on earlier Flutter versions as well.

**Comment by mikeroosa** [comment]
ok, the app is loading now. I updated tmdb_config.dart with an api key but I'm getting an error on all pages that says Error loading events.. I'll try to debug.

**Comment by mikeroosa** [comment]
in http_utils.dart in the getRequest, this is the error:
I/flutter (11316): Exception: SocketException: Failed host lookup: 'www.finnkino.fi' (OS Error: No address associated with hostname, errno = 7)

**Comment by mikeroosa** [comment]
Looks like my VPN was blocking the url. All good now.
