### ISSUE TITLE
Error: No dynamic found

### ISSUE THREAD

**Issue by raymondctc** [roughike/inKino#66]
I am using Flutter v0.2.8 and built the Android apk with `./gradlew installDebug`, when I open the app, it showed the following error.

![screenshot_20180412-100557](https://user-images.githubusercontent.com/13764117/38652622-5e5255e8-3e39-11e8-9430-a26e444aed52.png)

**Comment by roughike** [comment]
Hi, thanks for reporting!

Couldn't reproduce on a fresh clone.

Could you either:
* run `flutter channel beta && flutter upgrade` and try again
* if that doesn't work, run the app using `flutter run --preview-dart-2` command

If either one doesn't work, could you paste the output of `flutter doctor` here so I could get some more context?
