### ISSUE TITLE
Support Version differences between the Client and Server

### ISSUE THREAD

**Issue by gedw99** [roughike/inKino#67]
How do you handle the situation where you have V1 Client and v 1.1 server ?

There are a few techniques which i wil raise for discussion as i have tried a few difference ones.

1. Keep the URLs always the same and pass the version of the client in the header. The server then detects the version in the header and then handles the request this way. Not changing the URL is the whole point here as if you do then so much else has to constantly change.

2. Use GRPC. GRPC was designed so that the client and server can use have Data type models that are different in that if a field is added to the server model the client does not freak out.

Maybe some others.... ?

**Comment by roughike** [comment]
Hi! I'm not sure if this is needed for this app. I don't really control the API, and it has stayed the same for years anyway. The API also doesn't support versioning.

I'll close this one for now and reopen if this ever becomes a problem.
