### ISSUE TITLE
ChromeOS issues list

### ISSUE THREAD

**Issue by gedw99** [roughike/inKino#74]
I tried it out on Chrome OS and found a few things not right, but in general it works 👍 

- No langscape mode. I think i raised this in a seperate issue. This is the most pressing issue.
- Escape works, which is the same as the back button. SO thats good. I guess its default
- Tabbing does not work. This is really important. For example the Google Play store on ChromeOS allows you to use TAB key to jump down and across lists, and then ESC to back up out of lists or all the way backwards in navigation. It makes it much more usable.
- everything works !!

**Comment by roughike** [comment]
Thanks for reporting! So, seems like landscape and tabbing are issues, otherwise everything works. The landscape issue existed already, but I created a separate issue about the tabbing issue. I'll close this one since now there's a specific ticket for both problems.
