### ISSUE TITLE
Dropping all `new` and `const` keywords?

### ISSUE THREAD

**Issue by jaychang0917** [roughike/inKino#77]
A great redux example! 

Any thoughts about migrating the code to dart 2?

**Comment by roughike** [comment]
Hey!

What do you mean about migrating to Dart 2? I consider it migrated already.

If you mean dropping all `new` and `const` keywords, I didn't do that just yet, since from what I heard, that feature is not ready just yet.

**Comment by jaychang0917** [comment]
Ya, i mean dropping all `new` and `const` keywords.

But I just created a test app, remove all `new` and `const`, it can build into the device.

**Comment by roughike** [comment]
Nice to hear that it's working!

I would still wait until they say that the feature is ready. According to this article: https://medium.com/flutter-io/https-medium-com-flutter-io-announcing-flutters-beta-2-c85ba1557d5e

> During our final testing of beta 2 we found a number of issues so for now we recommend postponing any non-experimental use of optional new/const until we launch a new beta build declaring it ready.

I really want to wait until they consider it ready. After that, I'm happy to do it.
