### ISSUE TITLE
Equals implementation of ViewModels incorrect

### ISSUE THREAD

**Issue by sir-boformer** [roughike/inKino#87]
Comparing 2 functions always returns false, even if the functions are the same. You have to exclude them in the equals comparison. Otherwise the view models are never equal, which means that the widget tree is rebuilt every time a store change occurs.

Example:
https://github.com/roughike/inKino/blob/development/lib/ui/events/events_page_view_model.dart#L38

**Comment by roughike** [comment]
Thanks for reporting! 

Pretty sure this was a quite big performance improvement. Just merged into the development branch.
