### ISSUE TITLE
Is it possible to use Stack ?

### ISSUE THREAD

**Issue by ejabu** [roughike/inKino#91]
https://github.com/roughike/inKino/blob/4e90d1b8e21e92453142c884e8df8feae85876d6/lib/ui/theater_list/theater_list.dart#L21

**Comment by roughike** [comment]
Try playing around with it; IIRC, the `StoreConnector` messed something up big time, but when using a `Stack`, the overscroll on iOS turned ugly. Can't really remember, but I'll take a look if I can sometime.

**Comment by ScratchMyPimples** [comment]
sir i can use this as a arcitecture for ordering app?

**Comment by roughike** [comment]
This is now fixed as I did it different way on the latest version.
