### ISSUE TITLE
I have a doubt about why override == operator and hashCode

### ISSUE THREAD

**Issue by marekchen** [roughike/inKino#93]
I have a doubt about why override == operator and hashCode

**Comment by marekchen** [comment]
@roughike Please help!

**Comment by roughike** [comment]
[See the conversation here.](https://github.com/roughike/inKino/commit/62a28d1ef7c6dfcb98cb3fd2ba7a092e684fce00#commitcomment-29442745)

To help this manual boilerplate, you could use `built_value`, but I didn't want to include it in this project, as at least at the time, it included some more manual steps in the build process.

**Comment by marekchen** [comment]
thank you very much!
