### ISSUE TITLE
PlatformAdaptiveProgressIndicator with 20% overhead in LoadingView

### ISSUE THREAD

**Issue by bluemix** [roughike/inKino#94]
Currently, the use of `PlatformAdaptiveProgressIndicator` in `LoadingView`
https://github.com/roughike/inKino/blob/6e1752ff4d5b1a9abfc8afbe86054581de56b1a1/lib/ui/events/events_page.dart#L32-L43
causing the app to continually running at about 20% overhead.

<img width="252" alt="screen shot 2018-08-03 at 22 16 02" src="https://user-images.githubusercontent.com/3332274/43661690-df20d358-976b-11e8-86e0-034136b1ce9a.png">

If I replace the `PlatformAdaptiveProgressIndicator` with only a `Text('Loading...')` this overhead is not occurring any more.

I found that `LoadingView` is using `StackView` to show/hide views depending on their visibility, 
https://github.com/roughike/inKino/blob/6e1752ff4d5b1a9abfc8afbe86054581de56b1a1/lib/ui/common/loading_view.dart#L115-L137

but I think that `PlatformAdaptiveProgressIndicator` keeps running in the background, although it is invisible.

I just wanted to note about this issues.

And, thanks for sharing this great project; 
I learned a lot from it 👍

**Comment by roughike** [comment]
Hmm, that's interesting... Thanks for reporting!

**Comment by roughike** [comment]
Fixed in the latest update! Thanks!
