### ISSUE TITLE
The expression here has a type of 'void', and therefore cannot be used.

### ISSUE THREAD

**Issue by ejabu** [roughike/inKino#95]
![image](https://user-images.githubusercontent.com/2019630/44011798-eb64d878-9ee4-11e8-877a-dd33de7f2a98.png)

```
void _updateShowDates(dynamic action, NextDispatcher next) {
    var now = Clock.getCurrentTime();
    var dates = List.generate(7, (index) => now.add(Duration(days: index)));

    next(new ShowDatesUpdatedAction(dates));
  }

```

I got this error message "The expression here has a type of 'void', and therefore cannot be used."

Detail 
- OS : Linux 18.04
- Flutter SDK : Channel dev, v0.5.8
- Dart version 2.0.0-dev.69.5.flutter-eab492385c

**Comment by roughike** [comment]
Wasn't able to reproduce with `0.7.3` beta. Feel free to reopen if the issue persists.
